[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "2.2.1"
tokio = { version = "1.12.0", features = ["full"] }
serde = "1.0.130"
serde_json = "1.0.68"
chrono = { version = "0.4.19", features = ["serde"] }
futures = "0.3.17"
thiserror = "1.0.31"
